version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10000:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    container_name: jupyter